[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
parchment-minecraft = "1.21.1"
parchment-mappings = "2024.11.17"

# Ice And Fire Community Edition
iceandfire-ce = "7524985"
uranus = "6979353"
jupiter = "7592856"

# Allthemodium
allthemodium = "7468993"
ato = "7027340"
geckolib = "7415496"

# FTB Quests
ftb-quests = "7429016"
ftb-teams = "7369021"
ftb-libray = "7420412"

[libraries]
# Ice And Fire Community Edition
mod-iceandfire-ce = { group = "curse.maven", name = "iceandfire-ce-1040076", version.ref = "iceandfire-ce" }
mod-uranus = { group = "curse.maven", name = "uranus-1010827", version.ref = "uranus" }
mod-jupiter = { group = "curse.maven", name = "jupiter-1072905", version.ref = "jupiter" }

# Allthemodium
mod-allthemodium = { group = "curse.maven", name = "allthemodium-364466", version.ref = "allthemodium" }
mod-ato = { group = "curse.maven", name = "ato-405593", version.ref = "ato" }
mod-geckolib = { group = "curse.maven", name = "geckolib-388172", version.ref = "geckolib" }

# FTB Quests
mod-ftb-quests = { group = "curse.maven", name = "ftb-quests-289412", version.ref = "ftb-quests" }
mod-ftb-teams = { group = "curse.maven", name = "ftb-teams-404468", version.ref = "ftb-teams" }
mod-ftb-libray = { group = "curse.maven", name = "ftb-libray-404465", version.ref = "ftb-libray" }
